apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: todolist-mongodb
build:
  artifacts:
    - image: client
      context: client
      docker:
        dockerfile: Dockerfile
    - image: server
      context: server
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/*.yaml
  helm:
    releases:
      - name: mongodb
        chartPath: mongodb
        
      - name: elasticsearch
        chartPath: elk/elasticsearch
        
      - name: logstash
        chartPath: elk/logstash
        
      - name: kibana
        chartPath: elk/kibana

      - name: filebeat
        chartPath: elk/filebeat

      # - name: grafana
      #   chartPath: grafana/grafana

      # - name: prometheus
      #   chartPath: prometheus/prometheus

      # - name: prometheus-mongodb-exporter
      #   chartPath: prometheus/prometheus-mongodb-exporter
