apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: server
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    app: server 
---
apiVersion: v1
kind: Service
metadata:
  name: server-headless
spec:
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: server